package com.busyqa.crm.model.academic;

public enum CourseName {
    AUTOMATION_TESTING,
    DATA_SCIENCE,
    SCRUM_MASTER,
    SOFTWARE_TESTING,
    AUTOMATION_TESTING_ONLINE,
    BUSINESS_ANALYSIS,
    DATA_SCIENCE_ONLINE,
    CERTIFIED_SCRUM_MASTER,
    FULLSTACK_JAVA_DEVELOPER,
    PERFORMANCE_TESTING,
    SOFTWARE_TESTING_ONLINE
}
